---
# Copyright (c) 2025 kk
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

# Generate ELK Cluster Passwords
# Run this playbook to generate all required passwords

- name: Generate ELK Cluster Passwords
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    password_length: 16
    password_chars: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*"

  tasks:
    - name: Generate elastic user password
      set_fact:
        elasticsearch_password: "{{ lookup('password', '/dev/null length=' + password_length|string + ' chars=' + password_chars) }}"

    - name: Generate kibana_system user password
      set_fact:
        kibana_password: "{{ lookup('password', '/dev/null length=' + password_length|string + ' chars=' + password_chars) }}"

    - name: Generate logstash_system user password
      set_fact:
        logstash_password: "{{ lookup('password', '/dev/null length=' + password_length|string + ' chars=' + password_chars) }}"

    - name: Generate beats_system user password
      set_fact:
        beats_password: "{{ lookup('password', '/dev/null length=' + password_length|string + ' chars=' + password_chars) }}"

    - name: Generate monitoring_agent user password
      set_fact:
        monitoring_password: "{{ lookup('password', '/dev/null length=' + password_length|string + ' chars=' + password_chars) }}"

    - name: Generate remote_monitoring_user password
      set_fact:
        remote_monitoring_password: "{{ lookup('password', '/dev/null length=' + password_length|string + ' chars=' + password_chars) }}"

    - name: Create passwords directory
      file:
        path: ./passwords
        state: directory
        mode: '0700'

    - name: Save passwords to files
      copy:
        content: "{{ item.value }}"
        dest: "./passwords/{{ item.key }}.txt"
        mode: '0600'
      loop:
        - { key: 'elasticsearch_password', value: "{{ elasticsearch_password }}" }
        - { key: 'kibana_password', value: "{{ kibana_password }}" }
        - { key: 'logstash_password', value: "{{ logstash_password }}" }
        - { key: 'beats_password', value: "{{ beats_password }}" }
        - { key: 'monitoring_password', value: "{{ monitoring_password }}" }
        - { key: 'remote_monitoring_password', value: "{{ remote_monitoring_password }}" }

    - name: Create vault file with all passwords
      copy:
        content: |
          # ELK Cluster Passwords
          # Generated on {{ ansible_date_time.iso8601 }}

          vault_elasticsearch_password: "{{ elasticsearch_password }}"
          vault_kibana_password: "{{ kibana_password }}"
          vault_logstash_password: "{{ logstash_password }}"
          vault_beats_password: "{{ beats_password }}"
          vault_monitoring_password: "{{ monitoring_password }}"
          vault_remote_monitoring_password: "{{ remote_monitoring_password }}"
        dest: "./passwords/vault.yml"
        mode: '0600'

    - name: Display generated passwords
      debug:
        msg: |
          ========================================
          ELK Cluster Passwords Generated
          ========================================

          Elasticsearch (elastic): {{ elasticsearch_password }}
          Kibana (kibana_system): {{ kibana_password }}
          Logstash (logstash_system): {{ logstash_password }}
          Beats (beats_system): {{ beats_password }}
          Monitoring (monitoring_agent): {{ monitoring_password }}
          Remote Monitoring (remote_monitoring_user): {{ remote_monitoring_password }}

          ========================================
          Passwords saved to ./passwords/ directory
          Vault file: ./passwords/vault.yml
          ========================================