# Copyright (c) 2025 kk
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

# ELK Cluster Inventory
# Production environment configuration

all:
  children:
    elasticsearch:
      hosts:
        devops-elk-es-01:
          ansible_host: 10.170.1.46
          ansible_user: devops
          node_roles: [master, data, ingest]
        devops-elk-es-02:
          ansible_host: 10.170.1.47
          ansible_user: devops
          node_roles: [master, data, ingest]
        devops-elk-es-03:
          ansible_host: 10.170.1.48
          ansible_user: devops
          node_roles: [master, data, ingest]
      vars:
        # Elasticsearch specific variables
        es_cluster_name: "elk-production"
        es_data_path: "/var/lib/elasticsearch"
        es_logs_path: "/var/log/elasticsearch"

    logstash:
      hosts:
        devops-elk-ls-01:
          ansible_host: 10.170.1.49
          ansible_user: devops
      vars:
        # Logstash specific variables
        logstash_workers: 4
        logstash_pipeline_batch_size: 125
        logstash_pipeline_batch_delay: 50

    kibana:
      hosts:
        devops-elk-kb-01:
          ansible_host: 10.170.1.50
          ansible_user: devops
      vars:
        # Kibana specific variables
        kibana_server_port: 5601
        kibana_server_host: "0.0.0.0"



  vars:
    # Global variables
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_pipelining: true
    ansible_gather_facts: true

    # ELK versions
    elasticsearch_version: "8.18.3"
    logstash_version: "8.18.3"
    kibana_version: "8.18.3"
    java_version: "17"

    # System configuration
    vm_max_map_count: 262144
    file_descriptor_limit: 65536

    # Network configuration
    tcp_keepalive_time: 300
    tcp_keepalive_intvl: 75
    tcp_keepalive_probes: 9

    # Security (should be in vault)
    elasticsearch_password: "{{ vault_elasticsearch_password }}"
    kibana_password: "{{ vault_kibana_password }}"